import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const p = await b.newPage({ viewport: { width: 900, height: 900 } });
p.on('pageerror', e => console.log('ERR', e.message));
await p.goto('http://localhost:8124/index.html', { waitUntil: 'load' });
await p.waitForFunction(() => window.__fente && document.getElementById('loading-overlay').classList.contains('hidden'), null, { timeout: 300000 });
await p.waitForTimeout(2000);
await p.evaluate(() => { document.querySelectorAll('.hud,#dock,#tour-card').forEach(e=>e && (e.style.display='none')); });
await p.evaluate(() => window.__soloMany(['plate-top','battery','_cables']));
await p.evaluate(() => window.__look2(3.2, 36, -46, 70, -90, 48));
await p.waitForTimeout(700);
await p.screenshot({ path: 'xt-1.png', timeout: 90000 });
await p.evaluate(() => window.__soloMany(['plate-top','_cables']));
await p.evaluate(() => window.__look2(3.2, 34, -46, 46, -110, 22));
await p.waitForTimeout(700);
await p.screenshot({ path: 'xt-2.png', timeout: 90000 });
await p.evaluate(() => window.__soloMany(['plate-top','vtx','vtx-mount','rx','esc','_cables']));
await p.evaluate(() => window.__look2(3.2, 30, -25, 120, 160, 20));
await p.waitForTimeout(700);
await p.screenshot({ path: 'xt-3.png', timeout: 90000 });
console.log('ok');
await b.close();
